name: Update submodule on dispatch

on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "chore: update novel submodule from dispatch" || echo "No changes"
          git push
